name: publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          npm --version
          npm install npm@7.5.4 ts-node
          npm install
          npm run gen
          git status
