name: publish
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependences
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm --version
          npm install --save-dev npm@7.5.4
          npm install
      #- name: Regen source files
      #  run: |
      #    npm run gen
      #    git status
      #- name: Commit changes
      #  run: |
      #    git add .
      #    git commit -avm 'regen model files'
      #    git push
      - name: Building generated package
        run: |
          npm run install-all
          npm run bootstrap
          npm run clean-cache
      - name: commot changes
        continue-on-error: true
        run: |
          git commit -avm 'update package-lock.json'
          git push
      - name: Publishing with lerna
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm run lerna
